"""
Moyennes sectorielles Damodaran — janvier 2025.
Source : https://pages.stern.nyu.edu/~adamodar/New_Home_Page/datafile/mgnroc.html
Mise à jour manuelle ~1x/an.

Unités : identiques à yfinance.
  - Ratios (per, pbv, ps, ev_ebitda…)  : nombre brut
  - Marges, ROE, ROA, rendements        : décimal (0.25 = 25 %)
  - debt_to_equity                       : pourcentage (45.0 = D/E de 0.45)
"""

from __future__ import annotations

DAMODARAN: dict[str, dict[str, float]] = {
    "Technology": {
        "per": 28.5,
        "forward_per": 23.8,
        "peg": 1.85,
        "price_to_book": 7.8,
        "price_to_sales": 4.6,
        "ev_ebitda": 18.5,
        "ev_revenue": 4.9,
        "roe": 0.235,
        "roa": 0.115,
        "gross_margin": 0.545,
        "operating_margin": 0.215,
        "net_margin": 0.142,
        "debt_to_equity": 50.4,
        "current_ratio": 2.1,
        "quick_ratio": 1.85,
        "revenue_growth": 0.082,
        "earnings_growth": 0.105,
        "dividend_yield": 0.008,
        "payout_ratio": 0.18,
    },
    "Healthcare": {
        "per": 22.4,
        "forward_per": 18.2,
        "peg": 1.92,
        "price_to_book": 3.8,
        "price_to_sales": 2.9,
        "ev_ebitda": 14.2,
        "ev_revenue": 3.1,
        "roe": 0.168,
        "roa": 0.082,
        "gross_margin": 0.548,
        "operating_margin": 0.148,
        "net_margin": 0.102,
        "debt_to_equity": 71.6,
        "current_ratio": 1.9,
        "quick_ratio": 1.5,
        "revenue_growth": 0.062,
        "earnings_growth": 0.078,
        "dividend_yield": 0.015,
        "payout_ratio": 0.28,
    },
    "Financial Services": {
        "per": 13.8,
        "forward_per": 11.5,
        "peg": 1.45,
        "price_to_book": 1.5,
        "price_to_sales": 2.5,
        "ev_ebitda": 9.5,
        "ev_revenue": 2.4,
        "roe": 0.124,
        "roa": 0.015,
        "gross_margin": 0.72,
        "operating_margin": 0.28,
        "net_margin": 0.185,
        "debt_to_equity": 250.0,
        "current_ratio": 1.2,
        "quick_ratio": 1.1,
        "revenue_growth": 0.052,
        "earnings_growth": 0.068,
        "dividend_yield": 0.022,
        "payout_ratio": 0.32,
    },
    "Consumer Discretionary": {
        "per": 22.8,
        "forward_per": 19.2,
        "peg": 1.78,
        "price_to_book": 5.2,
        "price_to_sales": 1.6,
        "ev_ebitda": 12.4,
        "ev_revenue": 1.8,
        "roe": 0.212,
        "roa": 0.082,
        "gross_margin": 0.352,
        "operating_margin": 0.102,
        "net_margin": 0.074,
        "debt_to_equity": 120.5,
        "current_ratio": 1.5,
        "quick_ratio": 1.0,
        "revenue_growth": 0.068,
        "earnings_growth": 0.085,
        "dividend_yield": 0.012,
        "payout_ratio": 0.24,
    },
    "Consumer Staples": {
        "per": 19.5,
        "forward_per": 17.2,
        "peg": 2.1,
        "price_to_book": 4.4,
        "price_to_sales": 1.4,
        "ev_ebitda": 13.8,
        "ev_revenue": 1.65,
        "roe": 0.186,
        "roa": 0.082,
        "gross_margin": 0.352,
        "operating_margin": 0.122,
        "net_margin": 0.078,
        "debt_to_equity": 84.5,
        "current_ratio": 1.4,
        "quick_ratio": 0.85,
        "revenue_growth": 0.038,
        "earnings_growth": 0.055,
        "dividend_yield": 0.026,
        "payout_ratio": 0.52,
    },
    "Energy": {
        "per": 11.8,
        "forward_per": 10.2,
        "peg": 1.22,
        "price_to_book": 1.8,
        "price_to_sales": 0.85,
        "ev_ebitda": 5.8,
        "ev_revenue": 1.05,
        "roe": 0.142,
        "roa": 0.072,
        "gross_margin": 0.378,
        "operating_margin": 0.122,
        "net_margin": 0.076,
        "debt_to_equity": 48.2,
        "current_ratio": 1.3,
        "quick_ratio": 0.95,
        "revenue_growth": 0.028,
        "earnings_growth": 0.042,
        "dividend_yield": 0.032,
        "payout_ratio": 0.38,
    },
    "Industrials": {
        "per": 20.4,
        "forward_per": 17.5,
        "peg": 1.72,
        "price_to_book": 3.5,
        "price_to_sales": 1.45,
        "ev_ebitda": 12.2,
        "ev_revenue": 1.55,
        "roe": 0.172,
        "roa": 0.072,
        "gross_margin": 0.348,
        "operating_margin": 0.112,
        "net_margin": 0.078,
        "debt_to_equity": 92.4,
        "current_ratio": 1.6,
        "quick_ratio": 1.1,
        "revenue_growth": 0.055,
        "earnings_growth": 0.068,
        "dividend_yield": 0.018,
        "payout_ratio": 0.35,
    },
    "Communication Services": {
        "per": 19.8,
        "forward_per": 16.8,
        "peg": 1.65,
        "price_to_book": 3.4,
        "price_to_sales": 2.4,
        "ev_ebitda": 10.2,
        "ev_revenue": 2.5,
        "roe": 0.176,
        "roa": 0.072,
        "gross_margin": 0.498,
        "operating_margin": 0.178,
        "net_margin": 0.114,
        "debt_to_equity": 78.4,
        "current_ratio": 1.5,
        "quick_ratio": 1.3,
        "revenue_growth": 0.062,
        "earnings_growth": 0.082,
        "dividend_yield": 0.014,
        "payout_ratio": 0.26,
    },
    "Utilities": {
        "per": 15.8,
        "forward_per": 14.2,
        "peg": 2.45,
        "price_to_book": 1.5,
        "price_to_sales": 1.45,
        "ev_ebitda": 9.8,
        "ev_revenue": 2.2,
        "roe": 0.098,
        "roa": 0.032,
        "gross_margin": 0.402,
        "operating_margin": 0.198,
        "net_margin": 0.112,
        "debt_to_equity": 168.4,
        "current_ratio": 0.85,
        "quick_ratio": 0.72,
        "revenue_growth": 0.025,
        "earnings_growth": 0.038,
        "dividend_yield": 0.035,
        "payout_ratio": 0.62,
    },
    "Real Estate": {
        "per": 28.5,
        "forward_per": 24.5,
        "peg": 3.1,
        "price_to_book": 1.5,
        "price_to_sales": 4.8,
        "ev_ebitda": 17.4,
        "ev_revenue": 5.2,
        "roe": 0.078,
        "roa": 0.032,
        "gross_margin": 0.568,
        "operating_margin": 0.285,
        "net_margin": 0.224,
        "debt_to_equity": 118.5,
        "current_ratio": 1.1,
        "quick_ratio": 1.0,
        "revenue_growth": 0.042,
        "earnings_growth": 0.052,
        "dividend_yield": 0.04,
        "payout_ratio": 0.72,
    },
    "Telecommunication": {
        "per": 16.5,
        "forward_per": 14.2,
        "peg": 2.1,
        "price_to_book": 1.8,
        "price_to_sales": 1.2,
        "ev_ebitda": 6.8,
        "ev_revenue": 1.65,
        "roe": 0.112,
        "roa": 0.042,
        "gross_margin": 0.512,
        "operating_margin": 0.152,
        "net_margin": 0.082,
        "debt_to_equity": 145.2,
        "current_ratio": 0.85,
        "quick_ratio": 0.72,
        "revenue_growth": 0.025,
        "earnings_growth": 0.038,
        "dividend_yield": 0.048,
        "payout_ratio": 0.72,
    },
    "Basic Materials": {
        "per": 14.2,
        "forward_per": 12.5,
        "peg": 1.48,
        "price_to_book": 2.4,
        "price_to_sales": 1.15,
        "ev_ebitda": 7.8,
        "ev_revenue": 1.25,
        "roe": 0.148,
        "roa": 0.072,
        "gross_margin": 0.302,
        "operating_margin": 0.118,
        "net_margin": 0.074,
        "debt_to_equity": 65.4,
        "current_ratio": 1.7,
        "quick_ratio": 1.1,
        "revenue_growth": 0.032,
        "earnings_growth": 0.048,
        "dividend_yield": 0.024,
        "payout_ratio": 0.34,
    },
    "Unknown": {
        "per": 20.0,
        "forward_per": 17.0,
        "peg": 1.8,
        "price_to_book": 3.5,
        "price_to_sales": 2.2,
        "ev_ebitda": 12.5,
        "ev_revenue": 2.5,
        "roe": 0.155,
        "roa": 0.072,
        "gross_margin": 0.42,
        "operating_margin": 0.15,
        "net_margin": 0.10,
        "debt_to_equity": 85.0,
        "current_ratio": 1.6,
        "quick_ratio": 1.2,
        "revenue_growth": 0.055,
        "earnings_growth": 0.068,
        "dividend_yield": 0.018,
        "payout_ratio": 0.32,
    },
}

# Alias courants yfinance → clés Damodaran
_ALIASES: dict[str, str] = {
    "Materials": "Basic Materials",
    "Consumer Cyclical": "Consumer Discretionary",
    "Consumer Defensive": "Consumer Staples",
    "Financial": "Financial Services",
    "Finance": "Financial Services",
    "Telecom": "Telecommunication",
    "Telecommunications": "Telecommunication",
    "Telecom Services": "Telecommunication",
}


def get_sector_avg(sector: str | None) -> dict[str, float]:
    key = sector or "Unknown"
    return DAMODARAN.get(key, DAMODARAN.get(_ALIASES.get(key, ""), DAMODARAN["Unknown"]))
